modLoader="javafml"
loaderVersion="[43,)"
license="Apache-2.0"
issueTrackerURL="https://github.com/xhyrom/lan-properties/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='${mod_description}'
authors="xhyrom"
logoFile="icon.png"
displayURL="https://modrinth.com/mod/lan-properties"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.20.3)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="AFTER"
side="BOTH"
