license="Apache-2.0"
issueTrackerURL="https://github.com/xhyrom/lan-properties/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="xhyrom"
description='''${mod_description}'''
logoFile="icon.png"

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21.1.200,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.20,1.20.3)"
ordering="NONE"
side="BOTH"